const CANCIONES = [
  {
    id: 1,
    titulo: "Amanecer",
    artista: "Marea Baja",
    album: "Lunes al sol",
    anio: 2026,
    duracion: 222,
    portada: "img/amanecer.jpg",
    audio: "audio/amanecer.mp3",
  },
  {
    id: 2,
    titulo: "Tramontana",
    artista: "Marea Baja",
    album: "Lunes al sol",
    anio: 2026,
    duracion: 195,
    portada: "img/tramontana.jpg",
    audio: "audio/tramontana.mp3",
  },
  {
    id: 3,
    titulo: "Cielo raso",
    artista: "Nieve Suelta",
    album: "Enero",
    anio: 2025,
    duracion: 301,
    portada: "img/cieloraso.jpg",
    audio: "audio/cieloraso.mp3",
  },
  {
    id: 4,
    titulo: "Andén 4",
    artista: "Nieve Suelta",
    album: "Enero",
    anio: 2025,
    duracion: 178,
    portada: "img/anden4.jpg",
    audio: "audio/anden4.mp3",
  },
];
